name: movie_match
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  country_flags: ^4.1.2
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.2.0
  flutter_dotenv: ^6.0.1
  # flutter_localizations:
  #   sdk: flutter
  google_fonts: ^8.2.0
  http: ^1.6.0
  intl: any
  path: ^1.9.1
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2+1
  youtube_player_iframe: ^6.0.2

  material_ui: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
